# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - master
    - dev

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: build
    jobs:
      - job:
        steps:
          - task: NodeTool@0
            displayName: Install node
            inputs:
              versionSpec: '16.x'

          - script: npm install
            displayName: Npm install

          - task: Bash@3
            displayName: Configure env files
            inputs:
              targetType: 'inline'
              script: |
                > .env.production
                echo "REACT_APP_API_URL = '$(ApiUrlProd)'" >> .env.production
                #!/bin/bash  
                valueprod=`cat .env.production`  
                echo "$valueprod"  

                > .env.development
                echo "REACT_APP_API_URL = '$(ApiUrlDev)'" >> .env.development
                #!/bin/bash  
                valuedev=`cat .env.development`  
                echo "$valuedev"  

          - script: npm run build:production -- --prod 
            displayName: Npm run build prod
            condition: contains(variables['Build.SourceBranch'], 'refs/heads/master')
          
          - script: npm run build:development -- --prod 
            displayName: Npm run build dev
            condition: contains(variables['Build.SourceBranch'], 'refs/heads/dev')

          - publish: build
            artifact: build
            displayName: Publish build

  - stage: deploy_dev
    displayName: Deploy to development
    condition: contains(variables['Build.SourceBranch'], 'refs/heads/dev')
    jobs:
      - deployment: DeployDev
        environment: DEV
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo Hello, development world!

  - stage: deploy_prod
    displayName: Deploy to production
    condition: contains(variables['Build.SourceBranch'], 'refs/heads/master')
    jobs:
      - deployment: DeployProd
        environment: PROD
        strategy:
          runOnce:
            deploy:
              steps:
                
                - task: DownloadPipelineArtifact@2
                  inputs:
                    buildType: 'current'
                    artifactName: 'build'
                    targetPath: '$(System.ArtifactsDirectory)'

                - script: |
                    cd $(System.ArtifactsDirectory)
                    ls

                - task: AzureCLI@1
                  inputs:
                    azureSubscription: 'name'
                    scriptLocation: 'inlineScript'
                    inlineScript: 'az storage blob upload-batch \
                      --destination \$web \
                      --account-name "azuremealforfamilytestfe" \
                      --account-key "$(StorageAccountKey)" \
                      --source "$(System.ArtifactsDirectory)"'