# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: build
    jobs:
      - job:
        steps:
          - task: NodeTool@0
            displayName: Install node
            inputs:
              versionSpec: '16.x'

          - script: npm install
            displayName: Npm install

          - task: Bash@3
            displayName: Configure env files
            inputs:
              targetType: 'inline'
              script: |
                > .env.production
                echo "REACT_APP_API_URL = '$(ApiUrlProd)'" >> .env.production
                #!/bin/bash  
                valueprod=`cat .env.production`  
                echo "$valueprod"  

                > .env.development
                echo "REACT_APP_API_URL = '$(ApiUrlDev)'" >> .env.development
                #!/bin/bash  
                valuedev=`cat .env.development`  
                echo "$valuedev"  

          - bash: echo $(Build.SourceBranch)

          - script: npm run build:production -- --prod 
            displayName: Npm run build prod
            condition: contains(variables['Build.SourceBranch'], 'refs/heads/master')
          
          - script: npm run build:development -- --prod 
            displayName: Npm run build dev
            condition: contains(variables['Build.SourceBranch'], 'refs/heads/dev')

          - publish: build
            artifact: build
            displayName: Publish build

  - stage: deploy_dev
    displayName: Deploy to development
    jobs:
      - deployment: DeployWeb
        environment: DEV
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo Hello, development world!

  - stage: deploy_prd
    displayName: Deploy to production
    jobs:
      - deployment: DeployWeb
        environment: PROD
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo Hello, production world!