# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: build
    jobs:
      - job:
        steps:
          - task: NodeTool@0
            displayName: Install node
            inputs:
              versionSpec: '16.x'

          - script: npm install
            displayName: Npm install

          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                > .env.production
                echo "REACT_APP_API_URL = 'http://ec2-3-85-57-118.compute-1.amazonaws.com:8081/api/'" >> .env.production
                #!/bin/bash  
                value=`cat .env.production`  
                echo "$value"  

          - script: npm run build:production -- --prod 
            displayName: Npm run build

          - publish: build
            artifact: build
            displayName: Publish build

  - stage: deploy_dev
    displayName: Deploy to development
    jobs:
      - deployment: DeployWeb
        environment: DEV
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo Hello, development world!

  - stage: deploy_prd
    displayName: Deploy to production
    jobs:
      - deployment: DeployWeb
        environment: PROD
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo Hello, production world!